import { useContext, useEffect, useState, Fragment } from "react"

// Headless UI
import { Popover, Transition } from "@headlessui/react"

// Heroicons
import {

    ShoppingBagIcon,

} from "@heroicons/react/24/outline"

// Next
import Link from "next/link"

// Next
import Head from "next/head"

// Styles
import styles from "../styles/Home.module.css"

// Context
import { ProductContext } from "../context/ProductContext"

// Commerce Layer
import {
    CommerceLayer,
    OrderContainer,
    OrderStorage,
    LineItemsContainer,
    LineItemsCount,
    LineItem,
    LineItemImage,
    LineItemName, LineItemQuantity, LineItemAmount, LineItemRemoveLink, TotalAmount, CheckoutLink
} from "@commercelayer/react-components"

// Components
import { Footer } from "./Footer"


export const Layout = ({ children }) => {
    const { token, allData } = useContext(ProductContext)

    const [origin, setOrigin] = useState("http://localhost:3000")

    useEffect(() => {
        setOrigin(location.origin)
    }, [])


    return (
        <CommerceLayer
            accessToken={token}
            endpoint={process.env.NEXT_PUBLIC_CL_BASE_ENDPOINT}
        >
            <OrderStorage persistKey="abc-002">
                <OrderContainer
                    attributes={{
                        cart_url: `${origin}`,
                        return_url: `${origin}`,
                        privacy_url: `${origin}`,
                    }}
                >                                                                    <LineItemsContainer>


                        <div className={styles.container}>
                            <Head>
                                <title>Campaign 01</title>
                                <meta
                                    name="description"
                                    content="Generated by create next app"
                                />
                                <link rel="icon" href="/favicon.ico" />
                            </Head>

                            <div >
                                {/* {allData && allData?.image && <img
                                    src={allData?.image?.url}
                                    alt={"okay"}
                                    className="absolute -z-0 h-full w-full object-cover object-center"
                                />} */}
                                {/* className={`bg-[url('https://cdn.sanity.io/images/z17lrfub/production/0a2348eb5500b7dee1776b933f83a3f654c10ac0-1920x1280.jpg')] object-cover object-center bg-cover bg-center`} */}

                                <header className="relative">
                                    {/* Top navigation */}
                                    <nav
                                        aria-label="Top"
                                        className="relative z-20 bg-white bg-opacity-90 backdrop-blur-xl backdrop-filter"
                                    >
                                        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
                                            <div className="flex h-16 items-center">


                                                {/* Logo */}
                                                <div className="ml-4 flex lg:ml-0">
                                                    <Link href="/">
                                                        <img
                                                            className="h-8 w-auto cursor-pointer"
                                                            src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=600"
                                                            alt=""
                                                        />
                                                    </Link>
                                                </div>



                                                <div className="ml-auto flex items-center">
                                                    {/* Shopping Cart */}
                                                    <Popover className="ml-4 flow-root text-sm lg:relative lg:ml-8 z-50">
                                                        <Popover.Button className="group -m-2 flex items-center p-2">
                                                            <ShoppingBagIcon
                                                                className="h-6 w-6 flex-shrink-0 text-gray-400 group-hover:text-gray-500"
                                                                aria-hidden="true"
                                                            />
                                                            <span className="ml-2 text-sm font-medium text-gray-700 group-hover:text-gray-800"><LineItemsCount /></span>
                                                            <span className="sr-only">items in cart, view bag</span>
                                                        </Popover.Button>
                                                        <Transition
                                                            as={Fragment}
                                                            enter="transition ease-out duration-200"
                                                            enterFrom="opacity-0"
                                                            enterTo="opacity-100"
                                                            leave="transition ease-in duration-150"
                                                            leaveFrom="opacity-100"
                                                            leaveTo="opacity-0"
                                                        >
                                                            <Popover.Panel className="absolute inset-x-0 top-16 mt-px bg-white pb-6 shadow-lg sm:px-2 lg:top-full lg:left-auto lg:right-0 lg:mt-3 lg:-mr-1.5 lg:w-80 lg:rounded-lg lg:ring-1 lg:ring-black lg:ring-opacity-5">
                                                                <h2 className="sr-only">Shopping Cart</h2>

                                                                <div className="mx-auto max-w-2xl px-4">

                                                                    <ul role="list" className="divide-y divide-gray-200">


                                                                        <LineItemsContainer>
                                                                            <LineItem>
                                                                                <div className="flex items-center py-6">

                                                                                    <LineItemImage className="h-16 w-16 flex-none rounded-md border border-gray-200"
                                                                                        width={50} />
                                                                                    <div className="ml-4 flex-auto">
                                                                                        <h3 className="font-medium text-gray-900">
                                                                                            <LineItemName />
                                                                                        </h3>
                                                                                        <LineItemQuantity max={10} className="block mt-1 text-xs py-1" />
                                                                                        {/* <Errors resource="lineItem" field="quantity" /> */}
                                                                                        <LineItemAmount />
                                                                                        <LineItemRemoveLink className='text-red-400 cursor-pointer text-xs block' />
                                                                                    </div>
                                                                                </div>
                                                                            </LineItem></LineItemsContainer>


                                                                    </ul>


                                                                    <p className="text-base">Total: <LineItemsContainer><TotalAmount className="text-base" /></LineItemsContainer></p>
                                                                    <CheckoutLink
                                                                        type="submit"
                                                                        className="w-full rounded-md border border-transparent bg-indigo-600 mt-6 py-2 px-4 text-center text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 focus:ring-offset-gray-50"
                                                                    />

                                                                </div>
                                                            </Popover.Panel>
                                                        </Transition>
                                                    </Popover>
                                                </div>
                                            </div>
                                        </div>
                                    </nav>
                                </header>

                                <main >
                                    {children}
                                </main>

                                <Footer />
                            </div>

                        </div></LineItemsContainer>
                </OrderContainer>
            </OrderStorage>
        </CommerceLayer>
    )
}
